services:
  - type: web
    name: mini-redis-dashboard-live
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MINI_REDIS_HOST
        value: 127.0.0.1
      - key: MINI_REDIS_PORT
        value: 8080
      - key: MINI_REDIS_AUTOSTART
        value: 1
